---
#
# Installing Filebeat
#

# Create directory for certification

- name: Make new directory for cert
  shell: mkdir -p /etc/pki/tls/certs

# Download SSL certificate:

- name: Download certificate
  get_url:
    url: https://raw.githubusercontent.com/logzio/public-certificates/master/COMODORSADomainValidationSecureServerCA.crt
    dest: /etc/pki/tls/certs
    
# Install Filebeat 

- name: Install Filebeat 
  yum:
   name: filebeat
    
# Replace Filebeat configuration to ship to Logz.io. 

- name: Replace default filebeat.yml configurations
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml

# Starting Filebeat

- name: Starting Filebeat
  service:
   name: filebeat
   state: started
