---
#
# Installing Metricbeat
#

# Install Metricbeat

- name: Install Metricbeat
  yum:
   name: metricbeat
   update_cache: yes
   
- name: Add Xpac
  lineinfile:
    destfile: /etc/elasticsearch/elasticsearch.yml
    regexp: 'xpac'
    line: 'xpack.security.enabled: false'

# Starting Metricbeat

- name: Starting Metricbeat
  service:
   name: metricbeat
   state: started
