---
#
# Installing Metricbeat
#

# Install Metricbeat

- name: Install Metricbeat
  yum:
   name: metricbeat
   update_cache: yes
   
# Starting Metricbeat

- name: Starting Metricbeat
  service:
   name: metricbeat
   state: started
